FROM mskcc/roslin-variant-mutect:1.1.4
# Base Dockerfile: https://github.com/mskcc/roslin-variant/blob/2.6.x/build/containers/mutect/1.1.4/Dockerfile

LABEL maintainer="C. Allan Bolipata (bolipatc@mskcc.org)" \
      version.image="1.0.0" \
      version.mutect="1.1.4" \
      version.java="6" \
      source.mutect="https://github.com/broadinstitute/mutect/releases/tag/1.1.4"

ENV MUTECT_VERSION 1.1.4
